import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Header } from '@/widgets';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.className} ${montserrat.variable} antialiased bg-[#F6F6F6]`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
