import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Header } from '@/widgets';
import { FeaturesProvider } from '@/shared/providers/features-provider';
import { getFeatures } from '@/shared/api';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'MamaDoc Booking',
  description: 'Generated by @Seitek2002',
};

export const viewport = {
  themeColor: '#ffffff',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const features = await getFeatures().catch(() => ({
    branches_enabled: false,
    paylink_enabled: false,
    paylink_by_organization: false,
    paylink_by_professional: false,
  }));

  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://iwork.operator.kg' />
        <link rel='dns-prefetch' href='https://iwork.operator.kg' />
      </head>
      <body className={`${montserrat.className} ${montserrat.variable} antialiased bg-[#F6F6F6]`}>
        <Header />
        <FeaturesProvider features={features}>
          <main>{children}</main>
        </FeaturesProvider>
      </body>
    </html>
  );
}
